apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wap-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: whackapod.PUBLIC_IP.xip.io
    http:
      paths:
      - path: /api/
        backend:
          serviceName: api
          servicePort: 8080
      - path: /admin/
        backend:
          serviceName: admin
          servicePort: 8080
      - path: /
        backend:
          serviceName: game
          servicePort: 8080
